version: '2'
services:
    db: 
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3307:3306"
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    app: 
        build: .
        entrypoint: ["/app/lib/startup.sh"]
        volumes: 
            - ".:/app"
        ports: 
            - 3001:3000
        depends_on:
            db:
              condition: service_healthy
        links:
            - db
        environment:
            DB_USER: user
            DB_NAME: app
            DB_PASSWORD: password
            DB_HOST: db
            ELASTICSEARCH_URL: http://elasticsearch_api:9200 
    elasticsearch_api:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - discovery.type=single-node